apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Dokapi
  description: Terminal-first reconnaissance shell
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/apps/Dokapi
  links:
    - url: https://github.com/gustav0thethird/Dokapi
      title: GitHub
      icon: github
  tags:
    - python
    - recon
    - cli
    - security
    - apps
spec:
  type: tool
  lifecycle: production
  owner: gtully
  system: apps
