site_name: Dokapi
site_description: Terminal-first reconnaissance shell
plugins:
- techdocs-core
nav:
- Dokapi Overview: index.md
- Installation: installation.md
- Usage: usage.md
- Architecture: architecture.md
- Core Features: features.md
- Output: output.md
- Potential Roadmap: roadmap.md
- Disclaimer: disclaimer.md
